# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy an already built Website App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See readme.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: template.dnf.deploy.website
run-name: Deploy Website App
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string
      listFilesBeforeDeploy:
        required: false
        type: boolean
        default: false
      artifactName: 
        type: string
        default: ApiSolutionBundle
      packagePath:
        type: string
        default: drop

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    environment:
      name: ${{ inputs.envCode }}
    env:
      generatedAppEnvName: ${{ vars.APP_NAME }}-${{ inputs.envCode }}

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifactName }}

    - name: List Files Before Deploy
      if: inputs.listFilesBeforeDeploy == true
      run: 
        tree ${{ env.GITHUB_ACTION_PATH }} /f /a
      continue-on-error: true
  
    - name: Create Runtime Variables
      id: vars
      shell: bash
      run: |
        readonly rundatetime=$(date +'%Y-%m-%dT%H:%M:%SZ')
        echo "rundatetime=$rundatetime" >> $GITHUB_OUTPUT
        readonly rundate=$(date +'%Y.%m.%d')
        echo "rundate=$rundate" >> $GITHUB_OUTPUT
        readonly commitbranch=$(echo ${GITHUB_REF#refs/heads/})
        echo "commitbranch=$commitbranch" >> $GITHUB_OUTPUT
        readonly commitsha=${GITHUB_SHA::6}
        echo "commitsha=$commitsha" >> $GITHUB_OUTPUT
      continue-on-error: true
    - name: Put Build Details in buildinfo.json
      shell: bash
      run: |
        echo -e -n "{\"buildDate\":\"${{ steps.vars.outputs.rundatetime }}\",\"buildNumber\":\"${{ steps.vars.outputs.rundate }}.${{ github.run_number }}\",\"buildId\":\"${{ github.run_id }}.${{ github.run_attempt }}\",\"run_id\":\"${{ github.run_id }}\",\"run_attempt\":\"${{ github.run_attempt }}\",\"run_number\":\"${{ github.run_number }}\",\"branchName\":\"${{ steps.vars.outputs.commitbranch }}\",\"commitHash\":\"${{ steps.vars.outputs.commitsha }}\"}" > ${{ env.GITHUB_ACTION_PATH }}buildinfo.json
      continue-on-error: true

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        #creds: ${{ secrets.AZURE_CREDENTIALS }}  # old way of doing this, but the secrets are not as secure...

    - name: Deploy WebApp Zip
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.generatedAppEnvName }}
        package: .
        #package: ${{ inputs.artifactName }} # fails...
        #package: ${{ inputs.packagePath }} # fails...

    - name: Logout and cleanup
      shell: bash
      run: |
        az logout
        az cache purge
        az account clear
